# Generated by Django 5.0.6 on 2024-07-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_price',
            field=models.IntegerField(),
        ),
    ]
