# Generated by Django 5.0.6 on 2024-07-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_room_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Avaialable'), ('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('UNAVAILABLE', 'Unavailable')], max_length=50),
        ),
    ]
