# Generated by Django 5.0.6 on 2024-07-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_room_description_alter_room_room_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_price',
            field=models.FloatField(),
        ),
    ]
